### ISSUE TITLE
Create UI sketches

### ISSUE THREAD

**Issue by bigreader** [bigreader/bootcamp-studyhelper#12]

**Comment by Harun9** [comment]
[Group project sketch.docx](https://github.com/bigreader/bootcamp-studyhelper/files/2959335/Group.project.sketch.docx)

**Comment by melissakocourek** [comment]
![IMG_8584](https://user-images.githubusercontent.com/46450079/54247495-318e2e80-4507-11e9-8c2c-3112e774d25e.jpg)
